# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

GET http://instaroom.app.elpassion.com/rooms
Accept: application/json
AccessToken: ya29.GlwtBus4J6lZAxTLIivTwtp0mWGEZI8GZfE5nx0Nv31X9EdDFxG9jMXK9la1SwWa_cf9NZ2qJU-AcIFumx6nGl_92y3FX5jVwKdbd-pgheZnwHdLkmyRHkJZxj32oA
###